// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxpTu3xOgYnaP0zAREhvNo_NHZ4Rf02g',
    appId: '1:1067110588656:web:4a7acbf6cbb4dd4ecf2235',
    messagingSenderId: '1067110588656',
    projectId: 'sowandgrow-e9056',
    authDomain: 'sowandgrow-e9056.firebaseapp.com',
    storageBucket: 'sowandgrow-e9056.appspot.com',
    measurementId: 'G-XTQMXT86GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3DyBpio3w9MXk5nKHVfWwsFduLhWCbE',
    appId: '1:1067110588656:android:78fa0a9959fd3b87cf2235',
    messagingSenderId: '1067110588656',
    projectId: 'sowandgrow-e9056',
    storageBucket: 'sowandgrow-e9056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4c8M5y8r7VAEU0OfFGGARj3QEpxrajic',
    appId: '1:1067110588656:ios:81cfc420880700a5cf2235',
    messagingSenderId: '1067110588656',
    projectId: 'sowandgrow-e9056',
    storageBucket: 'sowandgrow-e9056.appspot.com',
    iosBundleId: 'com.example.sowandgrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4c8M5y8r7VAEU0OfFGGARj3QEpxrajic',
    appId: '1:1067110588656:ios:81cfc420880700a5cf2235',
    messagingSenderId: '1067110588656',
    projectId: 'sowandgrow-e9056',
    storageBucket: 'sowandgrow-e9056.appspot.com',
    iosBundleId: 'com.example.sowandgrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxpTu3xOgYnaP0zAREhvNo_NHZ4Rf02g',
    appId: '1:1067110588656:web:a65232fd18995129cf2235',
    messagingSenderId: '1067110588656',
    projectId: 'sowandgrow-e9056',
    authDomain: 'sowandgrow-e9056.firebaseapp.com',
    storageBucket: 'sowandgrow-e9056.appspot.com',
    measurementId: 'G-TSTK0VGFXP',
  );
}
